package com.bone.iam.application.command.handler;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyLong;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import com.bone.iam.application.command.cmd.CreateRoleCommand;
import com.bone.iam.application.service.TenantQuotaEnforcer;
import com.bone.iam.domain.repository.RoleRepository;
import com.bone.iam.domain.role.Role;
import java.lang.reflect.Field;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

/**
 * CreateRoleCommandHandler 单元测试
 *
 * <p>覆盖：
 *
 * <ol>
 *   <li>正常创建角色 → 返回 ID
 *   <li>code 为空时自动从 name 生成
 *   <li>tenantId 为 null 时从 TenantContext 获取
 * </ol>
 */
@ExtendWith(MockitoExtension.class)
class CreateRoleCommandHandlerTest {

  @Mock RoleRepository roleRepository;
  @Mock TenantQuotaEnforcer tenantQuotaEnforcer;

  CreateRoleCommandHandler handler;

  @BeforeEach
  void setUp() {
    handler = new CreateRoleCommandHandler(roleRepository, tenantQuotaEnforcer);
  }

  @Test
  void createRoleWithExplicitCode() {
    CreateRoleCommand cmd = new CreateRoleCommand();
    cmd.setName("管理员");
    cmd.setCode("ADMIN_ROLE");
    cmd.setDescription("系统管理员角色");
    cmd.setTenantId(1L);

    when(roleRepository.save(any(Role.class)))
        .thenAnswer(
            invocation -> {
              Role role = invocation.getArgument(0);
              setField(role, "id", 5L);
              return role.getId();
            });

    Long result = handler.handle(cmd);

    assertThat(result).isEqualTo(5L);
    verify(tenantQuotaEnforcer, times(1)).assertCanAddRole(1L);
    verify(roleRepository, times(1)).save(any(Role.class));
  }

  @Test
  void blankCodeAutoGeneratedFromName() {
    CreateRoleCommand cmd = new CreateRoleCommand();
    cmd.setName("Data Editor");
    cmd.setCode("  ");
    cmd.setTenantId(1L);

    when(roleRepository.save(any(Role.class)))
        .thenAnswer(
            invocation -> {
              Role role = invocation.getArgument(0);
              setField(role, "id", 7L);
              return role.getId();
            });

    Long result = handler.handle(cmd);

    assertThat(result).isEqualTo(7L);
    verify(roleRepository, times(1)).save(any(Role.class));
  }

  @Test
  void nullTenantIdFallsBackToTenantContext() {
    CreateRoleCommand cmd = new CreateRoleCommand();
    cmd.setName("Test Role");
    cmd.setCode("TEST_ROLE");
    cmd.setTenantId(null);

    when(roleRepository.save(any(Role.class)))
        .thenAnswer(
            invocation -> {
              Role role = invocation.getArgument(0);
              setField(role, "id", 8L);
              return role.getId();
            });

    Long result = handler.handle(cmd);

    assertThat(result).isEqualTo(8L);
    // TenantContext.getTenantIdAsLong() 返回 null 时，fallback 到 0L
    verify(tenantQuotaEnforcer, times(1)).assertCanAddRole(anyLong());
  }

  private static void setField(Object obj, String name, Object value) {
    try {
      Field f = findField(obj.getClass(), name);
      f.setAccessible(true);
      f.set(obj, value);
    } catch (ReflectiveOperationException e) {
      throw new IllegalStateException(e);
    }
  }

  private static Field findField(Class<?> cls, String name) throws NoSuchFieldException {
    Class<?> c = cls;
    while (c != null) {
      try {
        return c.getDeclaredField(name);
      } catch (NoSuchFieldException ignored) {
        c = c.getSuperclass();
      }
    }
    throw new NoSuchFieldException(name);
  }
}
