spring:
  application:
    name: bone-tpa-server

  profiles:
    active: local

  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB

server:
  port: 8885

masterdata:
    service:
      url: http://example.com/api/policy

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    export:
      prometheus:
        enabled: true

#liteflow:
#  #规则文件路径
#  rule-source: config/*.el.xml

#liteflow:
#  rule-source-ext-data-map:
#    serverAddr: 127.0.0.1:8848
#    dataId: liteflow_rule
#    group: DEFAULT_GROUP
#    namespace: a1b53442-8d95-44e5-9987-dadde657f4b8
#    username: bone-boot
#    password: bone-boot