package com.bone.metadata.sdk.domain.annotation;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * 用于标识实体类字段对应的数据库列
 * @author 梅山 2023-10-1
 */
@Target(ElementType.FIELD)  // 适用于字段
@Retention(RetentionPolicy.RUNTIME)  // 运行时可访问
public @interface Column {
    String name() default "";  // 列名

    boolean nullable() default true;  // 是否允许为 NULL

    boolean unique() default false;  // 是否是唯一列

    boolean autoGenerated() default false;  // 是否自动生成值的列
}