package com.bone.metadata.sdk.domain.model;

import com.bone.core.domain.id.GenerationStrategy;
import lombok.Data;

// 移除@Data注解，显式添加必要的getter方法
public class ColumnMetadata {
    private final String name;  // 列名
    private final String fieldName; //对象字段名
    private final Class<?> type;  // 列的类型
    private final boolean isPrimaryKey;  // 是否为主键
    private final boolean isVersion;  // 是否为版本字段
    private final boolean isNullable;  // 是否允许为 null
    private final boolean isUnique;  // 是否为唯一字段
    private final boolean isAutoGenerated;  // 是否自动生成值的字段
    private final boolean isSoftDeleted;  // 是否为软删除字段
    private final GenerationStrategy generationStrategy;
    private final String customGenerator;
    private final String sequenceName;
    
    // 显式添加getter方法
    public String getName() {
        return name;
    }
    
    public boolean isPrimaryKey() {
        return isPrimaryKey;
    }
    
    public boolean isVersion() {
        return isVersion;
    }
    
    public boolean isSoftDeleted() {
        return isSoftDeleted;
    }
}

