--- #################### 数据库相关配置 ####################
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:bone}?useSSL=false&autoReconnect=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME:root}
    password: ${BONE_DB_PASSWORD}
    # 指定为HikariDataSource
    type: com.zaxxer.hikari.HikariDataSource
    # hikari连接池配置
    hikari:
      #连接池名
      pool-name: HikariCP
      #最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间，默认10分钟
      idle-timeout: 600000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 10
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒
      connection-timeout: 30000
      # 连接测试query
      connection-test-query: SELECT 1

  # Redis 配置。Redisson 默认的配置足够使用，一般不需要进行调优
  data:
    redis:
      host: ${BONE_REDIS_HOST:localhost}
      port: ${BONE_REDIS_PORT:6379}
      database: 0
      password: ${BONE_REDIS_PASSWORD}
  redis:
    host: ${BONE_REDIS_HOST:localhost}
    port: ${BONE_REDIS_PORT:6379}
    database: 0
    password: ${BONE_REDIS_PASSWORD}

server:
  port: 8885

--- #################### 服务保障相关配置 ####################

# Lock4j 配置项
lock4j:
  acquire-timeout: 3000 # 获取分布式锁超时时间，默认为 3000 毫秒
  expire: 30000 # 分布式锁的超时时间，默认为 30 毫秒

--- #################### 监控相关配置 ####################

# Actuator 监控端点的配置项
management:
  endpoints:
    web:
      base-path: /actuator # Actuator 提供的 API 接口的根目录。默认为 /actuator
      exposure:
        include: '*' # 需要开放的端点。默认值只打开 health 和 info 两个端点。通过设置 * ，可以开放所有端点。

# 日志文件配置
logging:
  level:
    # 数据访问层日志打印级别
    com.bone.lowcode.dal.mysql: debug

metadata:
  sdk:
    appcode: ${METADATA_SDK_APPCODE:bone-metadata}
    open: true
    secret: ${METADATA_SDK_SECRET:}
    url: ${METADATA_SDK_URL:http://localhost:9001}
    sqlpath: ${METADATA_SDK_SQL_PATH:classpath:/sql-templates/}


#################### eureka相关配置 ####################
eureka:
  instance:
    status-page-url: /actuator/info
    health-check-url-path: /actuator/health
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://172.20.0.14:8761/eureka/
      registry-fetch-interval-seconds: 5


#################### 登录模块相关配置 ####################
sa-token:
  disable: true #关闭权限功能
  sign:
    secret-key: ${SA_TOKEN_SECRET:}
  timeout: 28800
  token-name: Satoken
  alone-redis:
    database: 11
    host: 47.105.112.106
    port: 6379
    password: ${BONE_REDIS_PASSWORD:}
    connect-timeout: 10s


#####################################################################################################
##OSS
oss:
  ENDPOINT: http://oss-cn-hangzhou.aliyuncs.com
  ACCESSKEYID: ${OSS_ACCESS_KEY_ID:}
  ACCESSKEYSECRET: ${OSS_ACCESS_KEY_SECRET:}
  BUCKETNAME: bucket-pktest
  KEY: pktpaphotoclaim/
  VISITURL: https://bucket-pktest.oss-cn-hangzhou.aliyuncs.com/
##OSS

#####################################################################################################

