package com.bone.metadata.sdk.query.builder;

import com.bone.core.util.ReflectionUtil;
import com.bone.metadata.sdk.query.context.BatchInsertContext;
import com.bone.metadata.sdk.domain.query.BatchCompiledQuery;
import com.bone.metadata.sdk.domain.model.ColumnMetadata;
import com.bone.core.domain.extension.ExtensibleObject;

import java.util.*;
import java.util.stream.Collectors;

public class BatchInsertBuilder implements BatchQueryBuilder<BatchInsertContext> {

    @Override
    public BatchCompiledQuery build(BatchInsertContext ctx)  {
        var table = ctx.getTable();
        List<?> ents = ctx.getEntities();
        var cols = table.getColumns().stream()
                .filter(c->!c.isAutoGenerated()).toList();
        String columnList = cols.stream().map(ColumnMetadata::getName).collect(Collectors.joining(", "));
        String ph = cols.stream().map(c->":"+c.getName()).collect(Collectors.joining(", "));
        String sql = "INSERT INTO "+table.getName()+" ("+columnList+") VALUES ("+ph+")";

        var batch = new ArrayList<Map<String,Object>>();
        for(var e:ents){
            var m = new LinkedHashMap<String,Object>();
            for(var c:cols){
                m.put(c.getName(), ReflectionUtil.getFieldValue(e,c.getFieldName()));
            }
            if(e instanceof ExtensibleObject ext){
                ext.getExtraProperties().forEach((k,v)->m.put("ext_"+k,v));
            }
            batch.add(m);
        }
        return new BatchCompiledQuery(sql, batch);
    }
}
