package com.bone.metadata.sdk.query.builder;

import com.bone.core.domain.extension.ExtensibleObject;
import com.bone.core.util.ReflectionUtil;
import com.bone.metadata.sdk.domain.model.ColumnMetadata;
import com.bone.metadata.sdk.domain.model.TableMetadata;
import com.bone.metadata.sdk.domain.query.BatchCompiledQuery;
import com.bone.metadata.sdk.query.context.BatchUpdateContext;
import com.bone.metadata.sdk.support.util.SqlUtil;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

public class BatchUpdateBuilder implements BatchQueryBuilder<BatchUpdateContext> {

  @Override
  public BatchCompiledQuery build(BatchUpdateContext ctx) {
    TableMetadata table = ctx.getTable();
    ColumnMetadata pk = table.getPrimaryKey();
    List<?> ents = ctx.getEntities();

    // 取非主键、非自生成、非 version、非租户归属列作为更新列。
    // version 列由 SDK 原生乐观锁独占管理（DynamicUpdateBuilder）：批量更新不 bump、不护栏，
    // 故此处排除，避免把它当普通列覆盖成实体内存值（ADR-0031 D1.6：批量路径不支持乐观锁）。
    // 租户归属列（tenant_id）仅 INSERT 时从可信 TenantContext 写入一次，更新路径不可写（见 DynamicUpdateBuilder 同款护栏），
    // 排除它既契合 ADR-0029 单租户不变量，也关闭跨租户破坏向量。
    List<ColumnMetadata> updCols =
        table.getColumns().stream()
            .filter(
                c ->
                    !c.isPrimaryKey()
                        && !c.isAutoGenerated()
                        && !c.isVersion()
                        && !(table.isTenantScoped() && c == table.getTenantIdColumn()))
            .toList();

    String setClause =
        updCols.stream()
            .map(c -> c.getName() + " = :" + c.getName())
            .collect(Collectors.joining(", "));
    String whereTpl = pk.getName() + " = :" + pk.getName();

    String sql = "UPDATE " + table.getName() + " SET " + setClause + " WHERE " + whereTpl;

    List<Map<String, Object>> batch = new ArrayList<>();
    for (Object e : ents) {
      Map<String, Object> m = new LinkedHashMap<>();
      // 主键值
      m.put(
          pk.getName(),
          SqlUtil.toJdbcParameter(ReflectionUtil.getFieldValue(e, pk.getFieldName())));
      // 更新列值
      for (ColumnMetadata c : updCols) {
        m.put(
            c.getName(),
            SqlUtil.toJdbcParameter(ReflectionUtil.getFieldValue(e, c.getFieldName())));
      }
      // 扩展属性
      if (e instanceof ExtensibleObject ext) {
        @SuppressWarnings("unchecked")
        Map<String, Object> extraProps = ext.getExtraProperties();
        extraProps.forEach((k, v) -> m.put("ext_" + k, v));
      }
      batch.add(m);
    }
    return new BatchCompiledQuery(sql, batch);
  }
}
