package com.bone.metadata.sdk.query.builder;

import com.bone.core.domain.extension.ExtensibleObject;
import com.bone.core.domain.id.GenerationStrategy;
import com.bone.core.util.ReflectionUtil;
import com.bone.metadata.sdk.domain.model.ColumnMetadata;
import com.bone.metadata.sdk.domain.query.BatchCompiledQuery;
import com.bone.metadata.sdk.query.context.BatchInsertContext;
import com.bone.metadata.sdk.support.util.SqlUtil;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

public class BatchInsertBuilder implements BatchQueryBuilder<BatchInsertContext> {

  @Override
  public BatchCompiledQuery build(BatchInsertContext ctx) {
    var table = ctx.getTable();
    List<?> ents = ctx.getEntities();
    // 主键列：仅当策略为 IDENTITY（数据库自增）时排除，其他策略由应用层生成 ID 须包含
    // 非主键列：保持原有 isAutoGenerated 过滤逻辑
    var cols =
        table.getColumns().stream()
            .filter(
                c -> {
                  if (c.isPrimaryKey()) {
                    return c.getGenerationStrategy() != GenerationStrategy.IDENTITY;
                  }
                  return !c.isAutoGenerated();
                })
            .toList();
    String columnList =
        cols.stream().map(ColumnMetadata::getName).collect(Collectors.joining(", "));
    String ph = cols.stream().map(c -> ":" + c.getName()).collect(Collectors.joining(", "));
    String sql = "INSERT INTO " + table.getName() + " (" + columnList + ") VALUES (" + ph + ")";

    var batch = new ArrayList<Map<String, Object>>();
    ColumnMetadata tenantCol = table.getTenantIdColumn();
    for (var e : ents) {
      var m = new LinkedHashMap<String, Object>();
      for (var c : cols) {
        Object value;
        if (tenantCol != null && c == tenantCol) {
          // 插入时从可信 TenantContext 补/校正租户（ADR-0029 建议补充 #1）
          value = SqlUtil.toJdbcParameter(TenantFilterInjector.resolveInsertTenantValue(table, e));
        } else {
          value = SqlUtil.toJdbcParameter(ReflectionUtil.getFieldValue(e, c.getFieldName()));
        }
        // @Version 未赋值：DB 有 DEFAULT 0，但 insert 显式给列，置 0 维持一致性（ADR-0031 D1）
        if (c.isVersion() && value == null) {
          value = 0L;
        }
        m.put(c.getName(), value);
      }
      // 扩展属性
      if (e instanceof ExtensibleObject ext) {
        @SuppressWarnings("unchecked")
        Map<String, Object> extraProps = ext.getExtraProperties();
        extraProps.forEach((k, v) -> m.put("ext_" + k, v));
      }
      batch.add(m);
    }
    return new BatchCompiledQuery(sql, batch);
  }
}
