-- 已合并至仓库根目录 bone-init.sql（§5 exts_*）。本文件仅作对照，勿单独执行。
-- Studio 扩展管理表（前缀 exts_，与 metadata ext_data_* 区分）
CREATE TABLE IF NOT EXISTS exts_extension_point (
    id                  BIGINT          NOT NULL COMMENT '主键',
    tenant_id           BIGINT          NOT NULL DEFAULT 0 COMMENT '租户ID',
    point_name          VARCHAR(255)    NOT NULL COMMENT '扩展点名称',
    point_code          VARCHAR(200)    NOT NULL COMMENT '扩展点编码（通常为接口 FQCN）',
    description         TEXT,
    interface_name      VARCHAR(500)    NOT NULL COMMENT '扩展点接口 FQCN',
    biz_domain          VARCHAR(100)    DEFAULT NULL COMMENT '业务域',
    category            VARCHAR(100)    DEFAULT NULL COMMENT '分类',
    status              VARCHAR(20)     NOT NULL DEFAULT 'ENABLED',
    created_by          BIGINT          DEFAULT NULL,
    updated_by          BIGINT          DEFAULT NULL,
    created_at          DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at          DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted             TINYINT(1)      NOT NULL DEFAULT 0,
    version             INT             NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_exts_ep_code (tenant_id, point_code),
    KEY idx_exts_ep_tenant (tenant_id, status),
    KEY idx_exts_ep_iface (interface_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Studio 扩展点';

CREATE TABLE IF NOT EXISTS exts_extension_impl (
    id                  BIGINT          NOT NULL COMMENT '主键',
    tenant_id           BIGINT          NOT NULL DEFAULT 0,
    extension_point_id  BIGINT          NOT NULL,
    app_id              BIGINT          DEFAULT NULL,
    impl_name           VARCHAR(255)    NOT NULL,
    impl_code           VARCHAR(200)    NOT NULL,
    description         VARCHAR(500)    DEFAULT NULL,
    class_name          VARCHAR(500)    NOT NULL,
    tenant_code         VARCHAR(64)     DEFAULT '*',
    biz_code            VARCHAR(64)     DEFAULT '*',
    use_case            VARCHAR(64)     DEFAULT '*',
    scenario            VARCHAR(64)     DEFAULT '*',
    user_group          VARCHAR(64)     DEFAULT '*',
    priority            INT             NOT NULL DEFAULT 100,
    config_json         JSON            DEFAULT NULL,
    status              TINYINT         NOT NULL DEFAULT 1,
    is_default          TINYINT(1)      NOT NULL DEFAULT 0,
    rollout_percent     TINYINT         DEFAULT NULL,
    created_by          BIGINT          DEFAULT NULL,
    updated_by          BIGINT          DEFAULT NULL,
    created_at          DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at          DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted             TINYINT(1)      NOT NULL DEFAULT 0,
    version             INT             NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_exts_ei_code (extension_point_id, impl_code),
    KEY idx_exts_ei_tenant (tenant_id, extension_point_id),
    KEY idx_exts_ei_point (extension_point_id),
    KEY idx_exts_ei_app (app_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Studio 扩展实现';

CREATE TABLE IF NOT EXISTS exts_plugin_version (
    id                  BIGINT          NOT NULL COMMENT '主键',
    tenant_id           BIGINT          NOT NULL DEFAULT 0,
    plugin_id           BIGINT          NOT NULL,
    release_version     VARCHAR(50)     NOT NULL,
    file_path           VARCHAR(512)    NOT NULL,
    file_size           BIGINT          DEFAULT NULL,
    checksum            VARCHAR(64)     NOT NULL,
    is_active           TINYINT(1)      NOT NULL DEFAULT 0,
    deployment_status   VARCHAR(20)     NOT NULL DEFAULT 'STAGED',
    change_log          VARCHAR(500)    DEFAULT NULL,
    created_by          BIGINT          DEFAULT NULL,
    updated_by          BIGINT          DEFAULT NULL,
    created_at          DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at          DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted             TINYINT(1)      NOT NULL DEFAULT 0,
    version             INT             NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_exts_pv (plugin_id, release_version),
    KEY idx_exts_pv_tenant (tenant_id, plugin_id),
    KEY idx_exts_pv_plugin (plugin_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Studio 插件版本';

CREATE TABLE IF NOT EXISTS exts_plugin_execution_log (
    id                  BIGINT          NOT NULL COMMENT '主键',
    tenant_id           BIGINT          NOT NULL DEFAULT 0,
    plugin_id           BIGINT          NOT NULL,
    extension_point_id  BIGINT          NOT NULL,
    execution_id        VARCHAR(64)     NOT NULL,
    status              VARCHAR(20)     NOT NULL,
    input_data          JSON            DEFAULT NULL,
    output_data         JSON            DEFAULT NULL,
    error_message       TEXT,
    duration_ms         BIGINT          DEFAULT NULL,
    created_by          BIGINT          DEFAULT NULL,
    updated_by          BIGINT          DEFAULT NULL,
    created_at          DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at          DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted             TINYINT(1)      NOT NULL DEFAULT 0,
    version             INT             NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_exts_pel_exec (execution_id),
    KEY idx_exts_pel_tenant (tenant_id, plugin_id, created_at),
    KEY idx_exts_pel_plugin (plugin_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Studio 插件执行日志';
