-- Studio 扩展管理表（与平台 ext_* 模块命名对齐，字段适配 Studio 领域模型）
CREATE TABLE IF NOT EXISTS ext_studio_extension_point (
    id                  BIGINT          NOT NULL COMMENT '主键',
    tenant_id           BIGINT          NOT NULL DEFAULT 0 COMMENT '租户ID',
    point_name          VARCHAR(255)    NOT NULL COMMENT '扩展点名称',
    point_code          VARCHAR(200)    NOT NULL COMMENT '扩展点编码（通常为接口 FQCN）',
    description         TEXT,
    interface_name      VARCHAR(500)    NOT NULL COMMENT '扩展点接口 FQCN',
    biz_domain          VARCHAR(100)    DEFAULT NULL COMMENT '业务域',
    category            VARCHAR(100)    DEFAULT NULL COMMENT '分类',
    status              VARCHAR(20)     NOT NULL DEFAULT 'ENABLED',
    create_time         DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    update_time         DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    create_by           BIGINT          DEFAULT NULL,
    update_by           BIGINT          DEFAULT NULL,
    deleted             TINYINT(1)      NOT NULL DEFAULT 0,
    version             INT             NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_ext_studio_ep_code (tenant_id, point_code),
    KEY idx_ext_studio_ep_iface (interface_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Studio 扩展点';

CREATE TABLE IF NOT EXISTS ext_studio_extension_impl (
    id                  BIGINT          NOT NULL COMMENT '主键',
    tenant_id           BIGINT          NOT NULL DEFAULT 0,
    extension_point_id  BIGINT          NOT NULL,
    impl_name           VARCHAR(255)    NOT NULL,
    impl_code           VARCHAR(200)    NOT NULL,
    description         VARCHAR(500)    DEFAULT NULL,
    class_name          VARCHAR(500)    NOT NULL,
    tenant_code         VARCHAR(64)     DEFAULT 'DEFAULT',
    biz_code            VARCHAR(64)     DEFAULT '*',
    use_case            VARCHAR(64)     DEFAULT '*',
    scenario            VARCHAR(64)     DEFAULT '*',
    user_group          VARCHAR(64)     DEFAULT '*',
    priority            INT             NOT NULL DEFAULT 100,
    config_json         JSON            DEFAULT NULL,
    status              TINYINT         NOT NULL DEFAULT 1,
    is_default          TINYINT(1)      NOT NULL DEFAULT 0,
    rollout_percent     TINYINT         DEFAULT NULL,
    create_time         DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    update_time         DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    create_by           BIGINT          DEFAULT NULL,
    update_by           BIGINT          DEFAULT NULL,
    deleted             TINYINT(1)      NOT NULL DEFAULT 0,
    version             INT             NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_ext_studio_ei_code (extension_point_id, impl_code),
    KEY idx_ext_studio_ei_point (extension_point_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Studio 扩展实现';
