<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>bone-lowcode</artifactId>
        <groupId>com.bone.cloud</groupId>
        <version>1.0.0</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>bone-lowcode-infra</artifactId>

    <dependencies>

        <!-- Spring Cloud 基础 -->
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-bootstrap</artifactId>
        </dependency>

        <dependency>
            <groupId>com.bone.cloud</groupId>
            <artifactId>bone-cloud-core</artifactId>
            <version>1.0.0</version>
        </dependency>

        <!-- 依赖服务 -->
        <dependency>
            <groupId>com.bone.cloud</groupId>
            <artifactId>bone-module-system-api</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.bone.cloud</groupId>
            <artifactId>bone-infra-api</artifactId>
            <version>1.0.0</version>
        </dependency>

        <!-- 业务组件 -->
        <dependency>
            <groupId>com.bone.cloud</groupId>
            <artifactId>bone-spring-boot-starter-biz-operatelog</artifactId>
        </dependency>
        <dependency>
            <groupId>com.bone.cloud</groupId>
            <artifactId>bone-spring-boot-starter-biz-error-code</artifactId>
        </dependency>

        <!-- Web 相关 -->
        <dependency>
            <groupId>com.bone.cloud</groupId>
            <artifactId>bone-spring-boot-starter-security</artifactId>
        </dependency>

        <dependency>
            <groupId>com.github.xiaoymin</groupId>
            <artifactId>knife4j-openapi3-spring-boot-starter</artifactId>
            <version>4.0.0</version>
        </dependency>

        <!-- DB 相关 -->
        <dependency>
            <groupId>com.mysql</groupId>
            <artifactId>mysql-connector-j</artifactId>
        </dependency>

        <dependency>
            <groupId>org.mybatis</groupId>
            <artifactId>mybatis</artifactId>
            <version>3.5.11</version>
        </dependency>

        <dependency>
            <groupId>org.mybatis</groupId>
            <artifactId>mybatis-spring</artifactId>
            <version>3.0.1</version>
        </dependency>
        <dependency>
            <groupId>org.mybatis.spring.boot</groupId>
            <artifactId>mybatis-spring-boot-starter</artifactId>
            <version>3.0.1</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.data</groupId>
            <artifactId>spring-data-jdbc</artifactId>
            <version>3.0.2</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jdbc</artifactId>
            <version>3.0.2</version>
        </dependency>


        <!-- RPC 远程调用相关 -->
        <dependency>
            <groupId>com.bone.cloud</groupId>
            <artifactId>bone-spring-boot-starter-rpc</artifactId>
        </dependency>

        <!-- Registry 注册中心相关 -->
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>

        <!-- Config 配置中心相关 -->
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
        </dependency>

        <!-- 监控相关 -->
        <dependency>
            <groupId>com.bone.cloud</groupId>
            <artifactId>bone-spring-boot-starter-monitor</artifactId>
        </dependency>

        <dependency>
            <groupId>de.codecentric</groupId>
            <artifactId>spring-boot-admin-starter-server</artifactId>
            <!-- 实现 Spring Boot Admin Server 服务端 -->
        </dependency>

    </dependencies>
    <!--    <dependencies>-->
<!--        &lt;!&ndash; Spring Cloud 基础 &ndash;&gt;-->
<!--        <dependency>-->
<!--            <groupId>org.springframework.cloud</groupId>-->
<!--            <artifactId>spring-cloud-starter-bootstrap</artifactId>-->
<!--        </dependency>-->

<!--        <dependency>-->
<!--            <groupId>com.bone.cloud</groupId>-->
<!--            <artifactId>bone-spring-boot-starter-env</artifactId>-->
<!--        </dependency>-->

<!--        <dependency>-->
<!--            <groupId>com.bone.cloud</groupId>-->
<!--            <artifactId>bone-cloud-core</artifactId>-->
<!--            <version>1.0.0</version>-->
<!--        </dependency>-->

<!--        <dependency>-->
<!--            <groupId>com.bone.cloud</groupId>-->
<!--            <artifactId>bone-cloud-starter-core</artifactId>-->
<!--            <version>1.0.0</version>-->
<!--        </dependency>-->

<!--        <dependency>-->
<!--            <groupId>org.mapstruct</groupId>-->
<!--            <artifactId>mapstruct</artifactId>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>org.mapstruct</groupId>-->
<!--            <artifactId>mapstruct-jdk8</artifactId> &lt;!&ndash; use mapstruct-jdk8 for Java 8 or higher &ndash;&gt;-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>org.mapstruct</groupId>-->
<!--            <artifactId>mapstruct-processor</artifactId>-->
<!--        </dependency>-->

<!--&lt;!&ndash;        <dependency>&ndash;&gt;-->
<!--&lt;!&ndash;            <groupId>org.springframework.cloud</groupId>&ndash;&gt;-->
<!--&lt;!&ndash;            <artifactId>spring-cloud-openfeign-core</artifactId>&ndash;&gt;-->
<!--&lt;!&ndash;        </dependency>&ndash;&gt;-->

<!--        <dependency>-->
<!--            <groupId>org.springframework.cloud</groupId>-->
<!--            <artifactId>spring-cloud-starter-openfeign</artifactId>-->
<!--        </dependency>-->

<!--        <dependency>-->
<!--            <groupId>org.apache.skywalking</groupId>-->
<!--            <artifactId>apm-toolkit-trace</artifactId>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>org.apache.skywalking</groupId>-->
<!--            <artifactId>apm-toolkit-logback-1.x</artifactId>-->
<!--        </dependency>-->

<!--        &lt;!&ndash;mybatis jdbc&ndash;&gt;-->
<!--        <dependency>-->
<!--            <groupId>com.mysql</groupId>-->
<!--            <artifactId>mysql-connector-j</artifactId>-->
<!--        </dependency>-->

<!--        <dependency>-->
<!--            <groupId>org.mybatis</groupId>-->
<!--            <artifactId>mybatis</artifactId>-->
<!--            <version>3.5.10</version>-->
<!--        </dependency>-->

<!--        <dependency>-->
<!--            <groupId>org.mybatis</groupId>-->
<!--            <artifactId>mybatis-spring</artifactId>-->
<!--            <version>3.0.1</version>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>org.mybatis.spring.boot</groupId>-->
<!--            <artifactId>mybatis-spring-boot-starter</artifactId>-->
<!--            <version>3.0.1</version>-->
<!--        </dependency>-->

<!--        <dependency>-->
<!--            <groupId>org.springframework.data</groupId>-->
<!--            <artifactId>spring-data-jdbc</artifactId>-->
<!--            <version>3.0.2</version>-->
<!--        </dependency>-->

<!--        <dependency>-->
<!--            <groupId>org.springframework.boot</groupId>-->
<!--            <artifactId>spring-boot-starter-data-jdbc</artifactId>-->
<!--            <version>3.0.2</version>-->
<!--        </dependency>-->

<!--        &lt;!&ndash;end mybatis jdbc&ndash;&gt;-->

<!--        &lt;!&ndash; 业务组件 &ndash;&gt;-->
<!--&lt;!&ndash;        <dependency>-->
<!--            <groupId>com.bone.cloud</groupId>-->
<!--            <artifactId>bone-spring-boot-starter-biz-operatelog</artifactId>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>com.bone.cloud</groupId>-->
<!--            <artifactId>bone-spring-boot-starter-biz-dict</artifactId>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>com.bone.cloud</groupId>-->
<!--            <artifactId>bone-spring-boot-starter-biz-data-permission</artifactId>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>com.bone.cloud</groupId>-->
<!--            <artifactId>bone-spring-boot-starter-biz-tenant</artifactId>-->
<!--        </dependency>&ndash;&gt;-->

<!--        &lt;!&ndash; Web 相关 &ndash;&gt;-->
<!--       <dependency>-->
<!--            <groupId>com.bone.cloud</groupId>-->
<!--            <artifactId>bone-spring-boot-starter-security</artifactId>-->
<!--        </dependency>-->

<!--        <dependency>-->
<!--            <groupId>com.bone.cloud</groupId>-->
<!--            <artifactId>bone-spring-boot-starter-web</artifactId>-->
<!--        </dependency>-->

<!--        &lt;!&ndash; Registry 注册中心相关 &ndash;&gt;-->
<!--        <dependency>-->
<!--            <groupId>com.alibaba.cloud</groupId>-->
<!--            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>-->
<!--        </dependency>-->

<!--        &lt;!&ndash; Config 配置中心相关 &ndash;&gt;-->
<!--       <dependency>-->
<!--            <groupId>com.alibaba.cloud</groupId>-->
<!--            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>-->
<!--        </dependency>-->

<!--        &lt;!&ndash; 消息队列相关 &ndash;&gt;-->
<!--&lt;!&ndash;        <dependency>-->
<!--            <groupId>com.bone.cloud</groupId>-->
<!--            <artifactId>bone-spring-boot-starter-mq</artifactId>-->
<!--        </dependency>&ndash;&gt;-->

<!--        &lt;!&ndash; Test 测试相关 &ndash;&gt;-->
<!--&lt;!&ndash;        <dependency>-->
<!--            <groupId>com.bone.cloud</groupId>-->
<!--            <artifactId>bone-spring-boot-starter-test</artifactId>-->
<!--            <scope>test</scope>-->
<!--        </dependency>&ndash;&gt;-->

<!--        &lt;!&ndash; 监控相关 &ndash;&gt;-->
<!--&lt;!&ndash;        <dependency>-->
<!--            <groupId>com.bone.cloud</groupId>-->
<!--            <artifactId>bone-spring-boot-starter-monitor</artifactId>-->
<!--        </dependency>&ndash;&gt;-->

<!--    </dependencies>-->

</project>