<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.pkh.cloud</groupId>
        <artifactId>bone-boot</artifactId>
        <version>1.0.0</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <modules>
        <module>bone-tpa</module>
        <module>bone-tpa-api</module>
        <module>bone-tpa-facade</module>
        <module>bone-tpa-sdk</module>
        <module>bone-tpa-intelligent-adjustment</module>
        <module>bone-tpa-core</module>
        <module>bone-tpa-push</module>
    </modules>
    <artifactId>bone-tpa-saas</artifactId>
    <packaging>pom</packaging>

    <name>${project.artifactId}</name>
    <description>
        TPA-SAAS 样板工程
    </description>
</project>
