package com.bone.metadata.sdk.domain.spec;

import com.bone.core.annotation.Deleted;
import com.bone.core.annotation.Id;
import com.bone.core.annotation.Transient;
import com.bone.core.domain.id.GenerationStrategy;
import com.bone.core.domain.id.GeneratedValue;
import com.bone.core.domain.id.SequenceGenerator;
import com.bone.metadata.sdk.domain.annotation.*;
import com.bone.metadata.sdk.domain.exception.MetadataException;
import com.bone.metadata.sdk.domain.model.ColumnMetadata;
import com.bone.metadata.sdk.domain.model.TableMetadata;
import com.bone.metadata.sdk.support.util.SqlUtil;
import com.github.benmanes.caffeine.cache.Cache;
import com.github.benmanes.caffeine.cache.Caffeine;
import lombok.extern.slf4j.Slf4j;
import org.springframework.util.StringUtils;

import java.lang.reflect.Field;
import java.util.*;
import java.util.concurrent.TimeUnit;

/**
 * 元数据解析器，支持缓存。
 */
@Slf4j
public final class TableMetadataResolver {

    // 使用Caffeine实现的线程安全缓存
    private static final Cache<String, TableMetadata> METADATA_CACHE = Caffeine.newBuilder()
            .maximumSize(2000)  // 最大缓存容量
            .expireAfterAccess(100, TimeUnit.HOURS)  // 缓存过期时间
            .build();

    /**
     * 获取表元数据，如果缓存中有，则直接返回，否则解析并缓存。
     *
     * @param entityClass 实体类类型
     * @return TableMetadata
     */
    public static TableMetadata load(Class<?> entityClass) {
        return METADATA_CACHE.get(entityClass.getName(), key -> parseTableMetadata(entityClass));
    }

    /**
     * 解析 TableMetadata 核心逻辑
     *
     * @param entityClass 实体类类型
     * @return TableMetadata
     */
    private static TableMetadata parseTableMetadata(Class<?> entityClass) {
        Table tableAnn = entityClass.getAnnotation(Table.class);
        if (tableAnn == null) {
            throw new MetadataException("@Table annotation missing on " + entityClass.getName());
        }

        String tableName = tableAnn.value();
        if (tableName == null || tableName.trim().isEmpty()) {
            tableName = entityClass.getSimpleName().toLowerCase();
        }
        List<ColumnMetadata> columns = parseColumns(entityClass);

        log.debug("Parsed TableMetadata for table: {} with {} columns", tableName, columns.size());
        return new TableMetadata(tableName, columns);
    }

    /**
     * 解析实体类的列元数据（包括继承的字段）
     */
    private static List<ColumnMetadata> parseColumns(Class<?> entityClass) {
        List<ColumnMetadata> columns = new ArrayList<>();
        Set<String> processedFields = new HashSet<>();
        Class<?> currentClass = entityClass;

        // 遍历类及其父类，获取所有字段
        while (currentClass != null && currentClass != Object.class) {
            for (Field field : currentClass.getDeclaredFields()) {
                if (shouldProcessField(field, processedFields)) {
                    columns.add(buildColumnMetadata(field));
                    processedFields.add(field.getName());
                }
            }
            currentClass = currentClass.getSuperclass();
        }

        log.debug("Parsed {} columns from class {}", columns.size(), entityClass.getName());
        return columns;
    }

    /**
     * 判断字段是否需要处理（排除 @Transient 注解和重复字段）
     */
    private static boolean shouldProcessField(Field field, Set<String> processedFields) {
        return !field.isAnnotationPresent(Transient.class) && !processedFields.contains(field.getName());
    }

    /**
     * 构建 ColumnMetadata
     */
    private static ColumnMetadata buildColumnMetadata(Field field) {
        Column columnAnn = field.getAnnotation(Column.class);
        String columnName = resolveColumnName(field, columnAnn);
        GenerationStrategy generationStrategy = resolveGenerationStrategy(field);
        String customGenerator = resolveCustomGenerator(field);
        String sequenceName = resolveSequenceName(field);

        return new ColumnMetadata(
                columnName,
                field.getName(),
                field.getType(),
                field.isAnnotationPresent(Id.class),
                field.isAnnotationPresent(Version.class),
                columnAnn != null && columnAnn.nullable(),
                columnAnn != null && columnAnn.unique(),
                columnAnn != null && columnAnn.autoGenerated() || (generationStrategy == GenerationStrategy.IDENTITY),
                field.isAnnotationPresent(Deleted.class),
                generationStrategy,
                customGenerator,
                sequenceName
        );
    }

    /**
     * 解析列名，如果 Column 注解为空，则转换为蛇形命名
     */
    private static String resolveColumnName(Field field, Column columnAnn) {
    return (columnAnn != null && StringUtils.hasText(columnAnn.name()))
                ? columnAnn.name().trim()
                : SqlUtil.toSnakeCase(field.getName());
    }

    /**
     * 获取字段的生成策略
     */
    private static GenerationStrategy resolveGenerationStrategy(Field field) {
        GeneratedValue generatedValue = field.getAnnotation(GeneratedValue.class);
        return (generatedValue != null) ? generatedValue.strategy() : null;
    }

    /**
     * 处理主键的自定义生成器
     */
    private static String resolveCustomGenerator(Field field) {
        GeneratedValue generatedValue = field.getAnnotation(GeneratedValue.class);
        return (generatedValue != null && StringUtils.hasText(generatedValue.generator()))
                ? generatedValue.generator().trim()
                : null;
    }

    /**
     * 解析字段的序列生成策略
     */
    private static String resolveSequenceName(Field field) {
        SequenceGenerator sequenceGen = field.getAnnotation(SequenceGenerator.class);
        return (sequenceGen != null) ? sequenceGen.sequenceName().trim() : null;
    }

    /**
     * 清理缓存的方法，可以在应用重启时或需要时清除缓存
     */
    public static void clearCache() {
        METADATA_CACHE.invalidateAll();
        log.info("All metadata cache cleared.");
    }

    /**
     * 清理特定表的缓存
     */
    public static void clearCacheForTable(String tableName) {
        METADATA_CACHE.invalidate(tableName);
        log.info("Cache for table {} cleared.", tableName);
    }
}
