package com.bone.tpa.sdk.masterdb.model;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import io.swagger.v3.oas.annotations.media.Schema;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * 线下案件生成，由TPA发起的理赔时
 */
public class TbClaim implements Serializable {
    @TableId(value="tbclaim_id",type = IdType.AUTO)
    private Integer tbclaimId;

    /**
     * 太保的赔案号，发送成功之后，会更新该字段
     *
     * @mbg.generated
     */
    @Schema(description = "太保的赔案号，发送成功之后，会更新该字段")
    private String tbclaimBatchCode;

    /**
     * 理赔状态：1-受理，2-审核，3-完成，4-已撤销
     *
     * @mbg.generated
     */
    @Schema(description = "理赔状态：1-受理，2-审核，3-完成，4-已撤销")
    private String tbclaimCaseStatus;

    /**
     * 理赔状态细分,二级理赔状态此字段与caseStatus对应，caseStatus为2时有区分
     *       “1”：受理
     *      “2-1”：审核
     *      “2-2”:催缴问题件
     *      “3”：完成
     *      “4”：已撤销
     *
     * @mbg.generated
     */

    private String tbclaimCaseStatusSecond;

    /**
     * 问题件描述
     * 
     * 尊敬的客户XX,您2017年08月15日赔案号WD20170815003001的理赔申请经审核，需进一步补充部分影像资料。
     *
     * @mbg.generated
     */
    @Schema(description = "问题件描述 尊敬的客户XX,您2017年08月15日赔案号WD20170815003001的理赔申请经审核，需进一步补充部分影像资料。")
    private String tbclaimDescription;

    /**
     * 综意险赔案号
     *
     * @mbg.generated
     */
    @Schema(description = "综意险赔案号")
    private String tbclaimCaseCode;

    /**
     * 专门用于给太保发送用的，其实就是“PK0000000"+caseCode
     *
     * @mbg.generated
     */
    @Schema(description = "专门用于给太保发送用的，其实就是“PK0000000'+caseCode")
    private String tbclaimCaseCodeTb;

    /**
     * 理赔结论
     *
     * @mbg.generated
     */
    @Schema(description = "理赔结论")
    private String tbclaimResult;

    /**
     * 合计理赔金额（单位：元）
     *
     * @mbg.generated
     */
    @Schema(description = "合计理赔金额（单位：元）")
    private BigDecimal tbclaimPayMoney;

    /**
     * 收款人姓名
     *
     * @mbg.generated
     */
    @Schema(description = "收款人姓名")
    private String tbclaimReceivedName;

    /**
     * 开户银行名称
     *
     * @mbg.generated
     */
    @Schema(description = "开户银行名称")
    private String tbclaimReceivedBank;

    /**
     * 开户银行账号
     *
     * @mbg.generated
     */
    @Schema(description = "开户银行账号")
    private String tbclaimReceivedBankNo;

    /**
     * 支付方式
     * “1”：转账
     * “2”：现金
     * “3”：其他
     *
     * @mbg.generated
     */
    @Schema(description = "支付方式 “1”：转账 “2”：现金 “3”：其他")
    private String tbclaimPayType;

    /**
     * 结案日期，格式yyyy-mm-dd
     *
     * @mbg.generated
     */
    @Schema(description = "结案日期，格式yyyy-mm-dd")
    private String tbclaimCloseDate;

    /**
     * 就诊日期，格式yyyy-mm-dd
     *
     * @mbg.generated
     */
    @Schema(description = "就诊日期，格式yyyy-mm-dd")
    private String tbclaimVisitDate;

    /**
     * 被保人姓名
     *
     * @mbg.generated
     */
    @Schema(description = "被保人姓名")
    private String tbclaimName;

    /**
     * 被保人证件号
     *
     * @mbg.generated
     */
    @Schema(description = "被保人证件号")
    private String tbclaimBbrzjh;

    /**
     * 被保人证件类型代码，a-身份证
     * a	身份证	
     * p	士兵证	
     * c	护照	
     * d	军官证	
     * f	驾驶执照	
     * j	港澳居民来往内地通行证	
     * l	台湾同胞来往内地通行证	
     * g	虚拟身份证	
     * i	其他证件	
     *
     * @mbg.generated
     */

    private String tbclaimBbrzjlx;

    /**
     * 主被保人证件号
     *
     * @mbg.generated
     */
    @Schema(description = "主被保人证件号")
    private String tbclaimZbbrzjh;

    /**
     * 主被保人证件类型代码，a-身份证
     * a	身份证	
     * p	士兵证	
     * c	护照	
     * d	军官证	
     * f	驾驶执照	
     * j	港澳居民来往内地通行证	
     * l	台湾同胞来往内地通行证	
     * g	虚拟身份证	
     * i	其他证件	
     *
     * @mbg.generated
     */
    private String tbclaimZbbrzjlx;

    /**
     * 申请类型代码
     * CLAIM_APPLY_TYPE_ZH	综合医疗	
     * CLAIM_APPLY_TYPE_MJZ	门急诊医疗	
     * CLAIM_APPLY_TYPE_ZY	住院医疗	
     *
     * @mbg.generated
     */

    private String tbclaimApplyTypeCode;

    /**
     * 调用方案件的唯一标识，可空
     *
     * @mbg.generated
     */
    @Schema(description = "调用方案件的唯一标识，可空")
    private String tbclaimAjid;

    /**
     * 状态，-1-作废，1-未发送，2-发送成功，3-发送失败
     *
     * @mbg.generated
     */
    @Schema(description = "状态，-1-作废，1-未发送，2-发送成功，3-发送失败")
    private Integer tbclaimStatus;

    private String tbclaimMemo;

    private Date tbclaimCreatetime;

    private Date tbclaimUpdatetime;

    /**
     * 团单号
     *
     * @mbg.generated
     */
    @Schema(description = "团单号")
    private String tbclaimGroupPolicy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_claim
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 
     * @return tbclaim_id 
     */
    public Integer getTbclaimId() {
        return tbclaimId;
    }

    /**
     * 
     * @param tbclaimId 
     */
    public void setTbclaimId(Integer tbclaimId) {
        this.tbclaimId = tbclaimId;
    }

    /**
     * 太保的赔案号，发送成功之后，会更新该字段
     * @return tbclaim_batch_code 太保的赔案号，发送成功之后，会更新该字段
     */
    public String getTbclaimBatchCode() {
        return tbclaimBatchCode;
    }

    /**
     * 太保的赔案号，发送成功之后，会更新该字段
     * @param tbclaimBatchCode 太保的赔案号，发送成功之后，会更新该字段
     */
    public void setTbclaimBatchCode(String tbclaimBatchCode) {
        this.tbclaimBatchCode = tbclaimBatchCode;
    }

    /**
     * 理赔状态：1-受理，2-审核，3-完成，4-已撤销
     * @return tbclaim_case_status 理赔状态：1-受理，2-审核，3-完成，4-已撤销
     */
    public String getTbclaimCaseStatus() {
        return tbclaimCaseStatus;
    }

    /**
     * 理赔状态：1-受理，2-审核，3-完成，4-已撤销
     * @param tbclaimCaseStatus 理赔状态：1-受理，2-审核，3-完成，4-已撤销
     */
    public void setTbclaimCaseStatus(String tbclaimCaseStatus) {
        this.tbclaimCaseStatus = tbclaimCaseStatus;
    }

    /**
     * 理赔状态细分,二级理赔状态此字段与caseStatus对应，caseStatus为2时有区分
      “1”：受理
     “2-1”：审核
     “2-2”:催缴问题件
     “3”：完成
     “4”：已撤销
     * @return tbclaim_case_status_second 理赔状态细分,二级理赔状态此字段与caseStatus对应，caseStatus为2时有区分
      “1”：受理
     “2-1”：审核
     “2-2”:催缴问题件
     “3”：完成
     “4”：已撤销
     */
    public String getTbclaimCaseStatusSecond() {
        return tbclaimCaseStatusSecond;
    }

    /**
     * 理赔状态细分,二级理赔状态此字段与caseStatus对应，caseStatus为2时有区分
      “1”：受理
     “2-1”：审核
     “2-2”:催缴问题件
     “3”：完成
     “4”：已撤销
     * @param tbclaimCaseStatusSecond 理赔状态细分,二级理赔状态此字段与caseStatus对应，caseStatus为2时有区分
      “1”：受理
     “2-1”：审核
     “2-2”:催缴问题件
     “3”：完成
     “4”：已撤销
     */
    public void setTbclaimCaseStatusSecond(String tbclaimCaseStatusSecond) {
        this.tbclaimCaseStatusSecond = tbclaimCaseStatusSecond;
    }

    /**
     * 问题件描述

尊敬的客户XX,您2017年08月15日赔案号WD20170815003001的理赔申请经审核，需进一步补充部分影像资料。
     * @return tbclaim_description 问题件描述

尊敬的客户XX,您2017年08月15日赔案号WD20170815003001的理赔申请经审核，需进一步补充部分影像资料。
     */
    public String getTbclaimDescription() {
        return tbclaimDescription;
    }

    /**
     * 问题件描述

尊敬的客户XX,您2017年08月15日赔案号WD20170815003001的理赔申请经审核，需进一步补充部分影像资料。
     * @param tbclaimDescription 问题件描述

尊敬的客户XX,您2017年08月15日赔案号WD20170815003001的理赔申请经审核，需进一步补充部分影像资料。
     */
    public void setTbclaimDescription(String tbclaimDescription) {
        this.tbclaimDescription = tbclaimDescription;
    }

    /**
     * 综意险赔案号
     * @return tbclaim_case_code 综意险赔案号
     */
    public String getTbclaimCaseCode() {
        return tbclaimCaseCode;
    }

    /**
     * 综意险赔案号
     * @param tbclaimCaseCode 综意险赔案号
     */
    public void setTbclaimCaseCode(String tbclaimCaseCode) {
        this.tbclaimCaseCode = tbclaimCaseCode;
    }

    /**
     * 专门用于给太保发送用的，其实就是“PK0000000"+caseCode
     * @return tbclaim_case_code_tb 专门用于给太保发送用的，其实就是“PK0000000"+caseCode
     */
    public String getTbclaimCaseCodeTb() {
        return tbclaimCaseCodeTb;
    }

    /**
     * 专门用于给太保发送用的，其实就是“PK0000000"+caseCode
     * @param tbclaimCaseCodeTb 专门用于给太保发送用的，其实就是“PK0000000"+caseCode
     */
    public void setTbclaimCaseCodeTb(String tbclaimCaseCodeTb) {
        this.tbclaimCaseCodeTb = tbclaimCaseCodeTb;
    }

    /**
     * 理赔结论
     * @return tbclaim_result 理赔结论
     */
    public String getTbclaimResult() {
        return tbclaimResult;
    }

    /**
     * 理赔结论
     * @param tbclaimResult 理赔结论
     */
    public void setTbclaimResult(String tbclaimResult) {
        this.tbclaimResult = tbclaimResult;
    }

    /**
     * 合计理赔金额（单位：元）
     * @return tbclaim_pay_money 合计理赔金额（单位：元）
     */
    public BigDecimal getTbclaimPayMoney() {
        return tbclaimPayMoney;
    }

    /**
     * 合计理赔金额（单位：元）
     * @param tbclaimPayMoney 合计理赔金额（单位：元）
     */
    public void setTbclaimPayMoney(BigDecimal tbclaimPayMoney) {
        this.tbclaimPayMoney = tbclaimPayMoney;
    }

    /**
     * 收款人姓名
     * @return tbclaim_received_name 收款人姓名
     */
    public String getTbclaimReceivedName() {
        return tbclaimReceivedName;
    }

    /**
     * 收款人姓名
     * @param tbclaimReceivedName 收款人姓名
     */
    public void setTbclaimReceivedName(String tbclaimReceivedName) {
        this.tbclaimReceivedName = tbclaimReceivedName;
    }

    /**
     * 开户银行名称
     * @return tbclaim_received_bank 开户银行名称
     */
    public String getTbclaimReceivedBank() {
        return tbclaimReceivedBank;
    }

    /**
     * 开户银行名称
     * @param tbclaimReceivedBank 开户银行名称
     */
    public void setTbclaimReceivedBank(String tbclaimReceivedBank) {
        this.tbclaimReceivedBank = tbclaimReceivedBank;
    }

    /**
     * 开户银行账号
     * @return tbclaim_received_bank_no 开户银行账号
     */
    public String getTbclaimReceivedBankNo() {
        return tbclaimReceivedBankNo;
    }

    /**
     * 开户银行账号
     * @param tbclaimReceivedBankNo 开户银行账号
     */
    public void setTbclaimReceivedBankNo(String tbclaimReceivedBankNo) {
        this.tbclaimReceivedBankNo = tbclaimReceivedBankNo;
    }

    /**
     * 支付方式
“1”：转账
“2”：现金
“3”：其他
     * @return tbclaim_pay_type 支付方式
“1”：转账
“2”：现金
“3”：其他
     */
    public String getTbclaimPayType() {
        return tbclaimPayType;
    }

    /**
     * 支付方式
“1”：转账
“2”：现金
“3”：其他
     * @param tbclaimPayType 支付方式
“1”：转账
“2”：现金
“3”：其他
     */
    public void setTbclaimPayType(String tbclaimPayType) {
        this.tbclaimPayType = tbclaimPayType;
    }

    /**
     * 结案日期，格式yyyy-mm-dd
     * @return tbclaim_close_date 结案日期，格式yyyy-mm-dd
     */
    public String getTbclaimCloseDate() {
        return tbclaimCloseDate;
    }

    /**
     * 结案日期，格式yyyy-mm-dd
     * @param tbclaimCloseDate 结案日期，格式yyyy-mm-dd
     */
    public void setTbclaimCloseDate(String tbclaimCloseDate) {
        this.tbclaimCloseDate = tbclaimCloseDate;
    }

    /**
     * 就诊日期，格式yyyy-mm-dd
     * @return tbclaim_visit_date 就诊日期，格式yyyy-mm-dd
     */
    public String getTbclaimVisitDate() {
        return tbclaimVisitDate;
    }

    /**
     * 就诊日期，格式yyyy-mm-dd
     * @param tbclaimVisitDate 就诊日期，格式yyyy-mm-dd
     */
    public void setTbclaimVisitDate(String tbclaimVisitDate) {
        this.tbclaimVisitDate = tbclaimVisitDate;
    }

    /**
     * 被保人姓名
     * @return tbclaim_name 被保人姓名
     */
    public String getTbclaimName() {
        return tbclaimName;
    }

    /**
     * 被保人姓名
     * @param tbclaimName 被保人姓名
     */
    public void setTbclaimName(String tbclaimName) {
        this.tbclaimName = tbclaimName;
    }

    /**
     * 被保人证件号
     * @return tbclaim_bbrzjh 被保人证件号
     */
    public String getTbclaimBbrzjh() {
        return tbclaimBbrzjh;
    }

    /**
     * 被保人证件号
     * @param tbclaimBbrzjh 被保人证件号
     */
    public void setTbclaimBbrzjh(String tbclaimBbrzjh) {
        this.tbclaimBbrzjh = tbclaimBbrzjh;
    }

    /**
     * 被保人证件类型代码，a-身份证
a	身份证	
p	士兵证	
c	护照	
d	军官证	
f	驾驶执照	
j	港澳居民来往内地通行证	
l	台湾同胞来往内地通行证	
g	虚拟身份证	
i	其他证件	
     * @return tbclaim_bbrzjlx 被保人证件类型代码，a-身份证
a	身份证	
p	士兵证	
c	护照	
d	军官证	
f	驾驶执照	
j	港澳居民来往内地通行证	
l	台湾同胞来往内地通行证	
g	虚拟身份证	
i	其他证件	
     */
    public String getTbclaimBbrzjlx() {
        return tbclaimBbrzjlx;
    }

    /**
     * 被保人证件类型代码，a-身份证
a	身份证	
p	士兵证	
c	护照	
d	军官证	
f	驾驶执照	
j	港澳居民来往内地通行证	
l	台湾同胞来往内地通行证	
g	虚拟身份证	
i	其他证件	
     * @param tbclaimBbrzjlx 被保人证件类型代码，a-身份证
a	身份证	
p	士兵证	
c	护照	
d	军官证	
f	驾驶执照	
j	港澳居民来往内地通行证	
l	台湾同胞来往内地通行证	
g	虚拟身份证	
i	其他证件	
     */
    public void setTbclaimBbrzjlx(String tbclaimBbrzjlx) {
        this.tbclaimBbrzjlx = tbclaimBbrzjlx;
    }

    /**
     * 主被保人证件号
     * @return tbclaim_zbbrzjh 主被保人证件号
     */
    public String getTbclaimZbbrzjh() {
        return tbclaimZbbrzjh;
    }

    /**
     * 主被保人证件号
     * @param tbclaimZbbrzjh 主被保人证件号
     */
    public void setTbclaimZbbrzjh(String tbclaimZbbrzjh) {
        this.tbclaimZbbrzjh = tbclaimZbbrzjh;
    }

    /**
     * 主被保人证件类型代码，a-身份证
a	身份证	
p	士兵证	
c	护照	
d	军官证	
f	驾驶执照	
j	港澳居民来往内地通行证	
l	台湾同胞来往内地通行证	
g	虚拟身份证	
i	其他证件	
     * @return tbclaim_zbbrzjlx 主被保人证件类型代码，a-身份证
a	身份证	
p	士兵证	
c	护照	
d	军官证	
f	驾驶执照	
j	港澳居民来往内地通行证	
l	台湾同胞来往内地通行证	
g	虚拟身份证	
i	其他证件	
     */
    public String getTbclaimZbbrzjlx() {
        return tbclaimZbbrzjlx;
    }

    /**
     * 主被保人证件类型代码，a-身份证
a	身份证	
p	士兵证	
c	护照	
d	军官证	
f	驾驶执照	
j	港澳居民来往内地通行证	
l	台湾同胞来往内地通行证	
g	虚拟身份证	
i	其他证件	
     * @param tbclaimZbbrzjlx 主被保人证件类型代码，a-身份证
a	身份证	
p	士兵证	
c	护照	
d	军官证	
f	驾驶执照	
j	港澳居民来往内地通行证	
l	台湾同胞来往内地通行证	
g	虚拟身份证	
i	其他证件	
     */
    public void setTbclaimZbbrzjlx(String tbclaimZbbrzjlx) {
        this.tbclaimZbbrzjlx = tbclaimZbbrzjlx;
    }

    /**
     * 申请类型代码
CLAIM_APPLY_TYPE_ZH	综合医疗	
CLAIM_APPLY_TYPE_MJZ	门急诊医疗	
CLAIM_APPLY_TYPE_ZY	住院医疗	
     * @return tbclaim_apply_type_code 申请类型代码
CLAIM_APPLY_TYPE_ZH	综合医疗	
CLAIM_APPLY_TYPE_MJZ	门急诊医疗	
CLAIM_APPLY_TYPE_ZY	住院医疗	
     */
    public String getTbclaimApplyTypeCode() {
        return tbclaimApplyTypeCode;
    }

    /**
     * 申请类型代码
CLAIM_APPLY_TYPE_ZH	综合医疗	
CLAIM_APPLY_TYPE_MJZ	门急诊医疗	
CLAIM_APPLY_TYPE_ZY	住院医疗	
     * @param tbclaimApplyTypeCode 申请类型代码
CLAIM_APPLY_TYPE_ZH	综合医疗	
CLAIM_APPLY_TYPE_MJZ	门急诊医疗	
CLAIM_APPLY_TYPE_ZY	住院医疗	
     */
    public void setTbclaimApplyTypeCode(String tbclaimApplyTypeCode) {
        this.tbclaimApplyTypeCode = tbclaimApplyTypeCode;
    }

    /**
     * 调用方案件的唯一标识，可空
     * @return tbclaim_ajid 调用方案件的唯一标识，可空
     */
    public String getTbclaimAjid() {
        return tbclaimAjid;
    }

    /**
     * 调用方案件的唯一标识，可空
     * @param tbclaimAjid 调用方案件的唯一标识，可空
     */
    public void setTbclaimAjid(String tbclaimAjid) {
        this.tbclaimAjid = tbclaimAjid;
    }

    /**
     * 状态，-1-作废，1-未发送，2-发送成功，3-发送失败
     * @return tbclaim_status 状态，-1-作废，1-未发送，2-发送成功，3-发送失败
     */
    public Integer getTbclaimStatus() {
        return tbclaimStatus;
    }

    /**
     * 状态，-1-作废，1-未发送，2-发送成功，3-发送失败
     * @param tbclaimStatus 状态，-1-作废，1-未发送，2-发送成功，3-发送失败
     */
    public void setTbclaimStatus(Integer tbclaimStatus) {
        this.tbclaimStatus = tbclaimStatus;
    }

    /**
     * 
     * @return tbclaim_memo 
     */
    public String getTbclaimMemo() {
        return tbclaimMemo;
    }

    /**
     * 
     * @param tbclaimMemo 
     */
    public void setTbclaimMemo(String tbclaimMemo) {
        this.tbclaimMemo = tbclaimMemo;
    }

    /**
     * 
     * @return tbclaim_createTime 
     */
    public Date getTbclaimCreatetime() {
        return tbclaimCreatetime;
    }

    /**
     * 
     * @param tbclaimCreatetime 
     */
    public void setTbclaimCreatetime(Date tbclaimCreatetime) {
        this.tbclaimCreatetime = tbclaimCreatetime;
    }

    /**
     * 
     * @return tbclaim_updateTime 
     */
    public Date getTbclaimUpdatetime() {
        return tbclaimUpdatetime;
    }

    /**
     * 
     * @param tbclaimUpdatetime 
     */
    public void setTbclaimUpdatetime(Date tbclaimUpdatetime) {
        this.tbclaimUpdatetime = tbclaimUpdatetime;
    }

    /**
     * 团单号
     * @return tbclaim_group_policy 团单号
     */
    public String getTbclaimGroupPolicy() {
        return tbclaimGroupPolicy;
    }

    /**
     * 团单号
     * @param tbclaimGroupPolicy 团单号
     */
    public void setTbclaimGroupPolicy(String tbclaimGroupPolicy) {
        this.tbclaimGroupPolicy = tbclaimGroupPolicy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_claim
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", tbclaimId=").append(tbclaimId);
        sb.append(", tbclaimBatchCode=").append(tbclaimBatchCode);
        sb.append(", tbclaimCaseStatus=").append(tbclaimCaseStatus);
        sb.append(", tbclaimCaseStatusSecond=").append(tbclaimCaseStatusSecond);
        sb.append(", tbclaimDescription=").append(tbclaimDescription);
        sb.append(", tbclaimCaseCode=").append(tbclaimCaseCode);
        sb.append(", tbclaimCaseCodeTb=").append(tbclaimCaseCodeTb);
        sb.append(", tbclaimResult=").append(tbclaimResult);
        sb.append(", tbclaimPayMoney=").append(tbclaimPayMoney);
        sb.append(", tbclaimReceivedName=").append(tbclaimReceivedName);
        sb.append(", tbclaimReceivedBank=").append(tbclaimReceivedBank);
        sb.append(", tbclaimReceivedBankNo=").append(tbclaimReceivedBankNo);
        sb.append(", tbclaimPayType=").append(tbclaimPayType);
        sb.append(", tbclaimCloseDate=").append(tbclaimCloseDate);
        sb.append(", tbclaimVisitDate=").append(tbclaimVisitDate);
        sb.append(", tbclaimName=").append(tbclaimName);
        sb.append(", tbclaimBbrzjh=").append(tbclaimBbrzjh);
        sb.append(", tbclaimBbrzjlx=").append(tbclaimBbrzjlx);
        sb.append(", tbclaimZbbrzjh=").append(tbclaimZbbrzjh);
        sb.append(", tbclaimZbbrzjlx=").append(tbclaimZbbrzjlx);
        sb.append(", tbclaimApplyTypeCode=").append(tbclaimApplyTypeCode);
        sb.append(", tbclaimAjid=").append(tbclaimAjid);
        sb.append(", tbclaimStatus=").append(tbclaimStatus);
        sb.append(", tbclaimMemo=").append(tbclaimMemo);
        sb.append(", tbclaimCreatetime=").append(tbclaimCreatetime);
        sb.append(", tbclaimUpdatetime=").append(tbclaimUpdatetime);
        sb.append(", tbclaimGroupPolicy=").append(tbclaimGroupPolicy);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}
