package com.bone.tpa.sdk.masterdb.model;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import io.swagger.v3.oas.annotations.media.Schema;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * 理赔结案分责任数据
 */
public class TbOverDuty implements Serializable {
    /**
     * 主键
     *
     * @mbg.generated
     */
    @Schema(description = "主键")


    @TableId(value="duty_id",type = IdType.AUTO)
    private Integer dutyId;

    /**
     * 理算ID
     *
     * @mbg.generated
     */
    @Schema(description = "理算ID")
    private String adjustmentguid;

    /**
     * 责任ID（不一定正确）
     *
     * @mbg.generated
     */
    @Schema(description = "责任ID（不一定正确）")
    private String relatedobjectguid;

    /**
     * 批次号
     *
     * @mbg.generated
     */
    @Schema(description = "批次号")
    private String dutyBatchCode;

    /**
     * 主单号
     *
     * @mbg.generated
     */
    @Schema(description = "主单号")
    private String dutyGroupPolicy;

    /**
     * 赔案号
     *
     * @mbg.generated
     */
    @Schema(description = "赔案号")
    private String dutyClaimCode;

    /**
     * 专门用于给太保发送用的，其实就是“PK0000000"+caseCode
     *
     * @mbg.generated
     */
    @Schema(description = "专门用于给太保发送用的，其实就是“PK0000000'+caseCode")
    private String dutyClaimCodeTb;

    /**
     * 投保序号
     *
     * @mbg.generated
     */
    @Schema(description = "投保序号")
    private String dutyCorpCode;

    /**
     * 身份证号
     *
     * @mbg.generated
     */
    @Schema(description = "身份证号")
    private String dutyPersonCertid;

    /**
     * 就诊责任
     *
     * @mbg.generated
     */
    @Schema(description = "就诊责任")
    private String dutyVisitDuty;

    /**
     * 就诊次数
     *
     * @mbg.generated
     */
    @Schema(description = "就诊次数")
    private Integer dutyVisitCount;

    /**
     * 申请金额
     *
     * @mbg.generated
     */
    @Schema(description = "申请金额")
    private BigDecimal dutyApplyAmt;

    /**
     * 免赔额
     *
     * @mbg.generated
     */
    @Schema(description = "免赔额")
    private BigDecimal dutyAbtmAmt;

    /**
     * 赔付金额
     *
     * @mbg.generated
     */
    @Schema(description = "赔付金额")
    private BigDecimal dutyCompensateAmt;

    /**
     * 调整金额
     *
     * @mbg.generated
     */
    @Schema(description = "调整金额")
    private BigDecimal dutyChangeAmt;

    /**
     * 剩余保额
     *
     * @mbg.generated
     */
    @Schema(description = "剩余保额")
    private BigDecimal dutyResidueAmt;

    /**
     * 拒赔原因
     *
     * @mbg.generated
     */
    @Schema(description = "拒赔原因")
    private String dutyUnCompensateCause;

    /**
     * 保险开始日期
     *
     * @mbg.generated
     */
    @Schema(description = "保险开始日期")
    private String dutyPolicyBeginDate;

    /**
     * 保险结束日期
     *
     * @mbg.generated
     */
    @Schema(description = "保险结束日期")
    private String dutyPolicyEndDate;

    /**
     * 账单类型
     *
     * @mbg.generated
     */
    @Schema(description = "账单类型")
    private String dutyBillType;

    /**
     * 赔付责任
     *
     * @mbg.generated
     */
    @Schema(description = "赔付责任")
    private String dutyCompensateDuty;

    /**
     * 赔付比例
     *
     * @mbg.generated
     */
    @Schema(description = "赔付比例")
    private BigDecimal dutyCompensateRatio;

    /**
     * 发票金额
     *
     * @mbg.generated
     */
    @Schema(description = "发票金额")
    private BigDecimal dutyBillAmt;

    private Date dutyCreatetime;

    private Date dutyUpdatetime;

    /**
     * 状态，默认1，1-可以生成结案文件，2-成功生成结案文件，3-可以生成理赔通知书，-1-作废
     *
     * @mbg.generated
     */
    @Schema(description = "状态，默认1，1-可以生成结案文件，2-成功生成结案文件，3-可以生成理赔通知书，-1-作废")
    private Integer dutyStatus;

    /**
     * j保存生成文件的有关信息
     *
     * @mbg.generated
     */
    @Schema(description = "j保存生成文件的有关信息")
    private String dutyMemo;

    /**
     * 状态，默认1，0-太享福已撤案，1-可以生成结案文件，2-成功生成结案文件，3-可以生成理赔通知书，4-已完成，-1-作废 
     *
     * @mbg.generated
     */
    @Schema(description = "状态，默认1，0-太享福已撤案，1-可以生成结案文件，2-成功生成结案文件，3-可以生成理赔通知书，4-已完成，-1-作废 ")
    private String claimHeadNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_over_duty
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 主键
     * @return duty_id 主键
     */
    public Integer getDutyId() {
        return dutyId;
    }

    /**
     * 主键
     * @param dutyId 主键
     */
    public void setDutyId(Integer dutyId) {
        this.dutyId = dutyId;
    }

    /**
     * 理算ID
     * @return AdjustmentGuid 理算ID
     */
    public String getAdjustmentguid() {
        return adjustmentguid;
    }

    /**
     * 理算ID
     * @param adjustmentguid 理算ID
     */
    public void setAdjustmentguid(String adjustmentguid) {
        this.adjustmentguid = adjustmentguid;
    }

    /**
     * 责任ID（不一定正确）
     * @return RelatedObjectGuid 责任ID（不一定正确）
     */
    public String getRelatedobjectguid() {
        return relatedobjectguid;
    }

    /**
     * 责任ID（不一定正确）
     * @param relatedobjectguid 责任ID（不一定正确）
     */
    public void setRelatedobjectguid(String relatedobjectguid) {
        this.relatedobjectguid = relatedobjectguid;
    }

    /**
     * 批次号
     * @return duty_batch_code 批次号
     */
    public String getDutyBatchCode() {
        return dutyBatchCode;
    }

    /**
     * 批次号
     * @param dutyBatchCode 批次号
     */
    public void setDutyBatchCode(String dutyBatchCode) {
        this.dutyBatchCode = dutyBatchCode;
    }

    /**
     * 主单号
     * @return duty_group_policy 主单号
     */
    public String getDutyGroupPolicy() {
        return dutyGroupPolicy;
    }

    /**
     * 主单号
     * @param dutyGroupPolicy 主单号
     */
    public void setDutyGroupPolicy(String dutyGroupPolicy) {
        this.dutyGroupPolicy = dutyGroupPolicy;
    }

    /**
     * 赔案号
     * @return duty_claim_code 赔案号
     */
    public String getDutyClaimCode() {
        return dutyClaimCode;
    }

    /**
     * 赔案号
     * @param dutyClaimCode 赔案号
     */
    public void setDutyClaimCode(String dutyClaimCode) {
        this.dutyClaimCode = dutyClaimCode;
    }

    /**
     * 专门用于给太保发送用的，其实就是“PK0000000"+caseCode
     * @return duty_claim_code_tb 专门用于给太保发送用的，其实就是“PK0000000"+caseCode
     */
    public String getDutyClaimCodeTb() {
        return dutyClaimCodeTb;
    }

    /**
     * 专门用于给太保发送用的，其实就是“PK0000000"+caseCode
     * @param dutyClaimCodeTb 专门用于给太保发送用的，其实就是“PK0000000"+caseCode
     */
    public void setDutyClaimCodeTb(String dutyClaimCodeTb) {
        this.dutyClaimCodeTb = dutyClaimCodeTb;
    }

    /**
     * 投保序号
     * @return duty_corp_code 投保序号
     */
    public String getDutyCorpCode() {
        return dutyCorpCode;
    }

    /**
     * 投保序号
     * @param dutyCorpCode 投保序号
     */
    public void setDutyCorpCode(String dutyCorpCode) {
        this.dutyCorpCode = dutyCorpCode;
    }

    /**
     * 身份证号
     * @return duty_person_certId 身份证号
     */
    public String getDutyPersonCertid() {
        return dutyPersonCertid;
    }

    /**
     * 身份证号
     * @param dutyPersonCertid 身份证号
     */
    public void setDutyPersonCertid(String dutyPersonCertid) {
        this.dutyPersonCertid = dutyPersonCertid;
    }

    /**
     * 就诊责任
     * @return duty_visit_duty 就诊责任
     */
    public String getDutyVisitDuty() {
        return dutyVisitDuty;
    }

    /**
     * 就诊责任
     * @param dutyVisitDuty 就诊责任
     */
    public void setDutyVisitDuty(String dutyVisitDuty) {
        this.dutyVisitDuty = dutyVisitDuty;
    }

    /**
     * 就诊次数
     * @return duty_visit_count 就诊次数
     */
    public Integer getDutyVisitCount() {
        return dutyVisitCount;
    }

    /**
     * 就诊次数
     * @param dutyVisitCount 就诊次数
     */
    public void setDutyVisitCount(Integer dutyVisitCount) {
        this.dutyVisitCount = dutyVisitCount;
    }

    /**
     * 申请金额
     * @return duty_apply_amt 申请金额
     */
    public BigDecimal getDutyApplyAmt() {
        return dutyApplyAmt;
    }

    /**
     * 申请金额
     * @param dutyApplyAmt 申请金额
     */
    public void setDutyApplyAmt(BigDecimal dutyApplyAmt) {
        this.dutyApplyAmt = dutyApplyAmt;
    }

    /**
     * 免赔额
     * @return duty_abtm_amt 免赔额
     */
    public BigDecimal getDutyAbtmAmt() {
        return dutyAbtmAmt;
    }

    /**
     * 免赔额
     * @param dutyAbtmAmt 免赔额
     */
    public void setDutyAbtmAmt(BigDecimal dutyAbtmAmt) {
        this.dutyAbtmAmt = dutyAbtmAmt;
    }

    /**
     * 赔付金额
     * @return duty_compensate_amt 赔付金额
     */
    public BigDecimal getDutyCompensateAmt() {
        return dutyCompensateAmt;
    }

    /**
     * 赔付金额
     * @param dutyCompensateAmt 赔付金额
     */
    public void setDutyCompensateAmt(BigDecimal dutyCompensateAmt) {
        this.dutyCompensateAmt = dutyCompensateAmt;
    }

    /**
     * 调整金额
     * @return duty_change_amt 调整金额
     */
    public BigDecimal getDutyChangeAmt() {
        return dutyChangeAmt;
    }

    /**
     * 调整金额
     * @param dutyChangeAmt 调整金额
     */
    public void setDutyChangeAmt(BigDecimal dutyChangeAmt) {
        this.dutyChangeAmt = dutyChangeAmt;
    }

    /**
     * 剩余保额
     * @return duty_residue_amt 剩余保额
     */
    public BigDecimal getDutyResidueAmt() {
        return dutyResidueAmt;
    }

    /**
     * 剩余保额
     * @param dutyResidueAmt 剩余保额
     */
    public void setDutyResidueAmt(BigDecimal dutyResidueAmt) {
        this.dutyResidueAmt = dutyResidueAmt;
    }

    /**
     * 拒赔原因
     * @return duty_un_compensate_cause 拒赔原因
     */
    public String getDutyUnCompensateCause() {
        return dutyUnCompensateCause;
    }

    /**
     * 拒赔原因
     * @param dutyUnCompensateCause 拒赔原因
     */
    public void setDutyUnCompensateCause(String dutyUnCompensateCause) {
        this.dutyUnCompensateCause = dutyUnCompensateCause;
    }

    /**
     * 保险开始日期
     * @return duty_policy_begin_date 保险开始日期
     */
    public String getDutyPolicyBeginDate() {
        return dutyPolicyBeginDate;
    }

    /**
     * 保险开始日期
     * @param dutyPolicyBeginDate 保险开始日期
     */
    public void setDutyPolicyBeginDate(String dutyPolicyBeginDate) {
        this.dutyPolicyBeginDate = dutyPolicyBeginDate;
    }

    /**
     * 保险结束日期
     * @return duty_policy_end_date 保险结束日期
     */
    public String getDutyPolicyEndDate() {
        return dutyPolicyEndDate;
    }

    /**
     * 保险结束日期
     * @param dutyPolicyEndDate 保险结束日期
     */
    public void setDutyPolicyEndDate(String dutyPolicyEndDate) {
        this.dutyPolicyEndDate = dutyPolicyEndDate;
    }

    /**
     * 账单类型
     * @return duty_bill_type 账单类型
     */
    public String getDutyBillType() {
        return dutyBillType;
    }

    /**
     * 账单类型
     * @param dutyBillType 账单类型
     */
    public void setDutyBillType(String dutyBillType) {
        this.dutyBillType = dutyBillType;
    }

    /**
     * 赔付责任
     * @return duty_compensate_duty 赔付责任
     */
    public String getDutyCompensateDuty() {
        return dutyCompensateDuty;
    }

    /**
     * 赔付责任
     * @param dutyCompensateDuty 赔付责任
     */
    public void setDutyCompensateDuty(String dutyCompensateDuty) {
        this.dutyCompensateDuty = dutyCompensateDuty;
    }

    /**
     * 赔付比例
     * @return duty_compensate_ratio 赔付比例
     */
    public BigDecimal getDutyCompensateRatio() {
        return dutyCompensateRatio;
    }

    /**
     * 赔付比例
     * @param dutyCompensateRatio 赔付比例
     */
    public void setDutyCompensateRatio(BigDecimal dutyCompensateRatio) {
        this.dutyCompensateRatio = dutyCompensateRatio;
    }

    /**
     * 发票金额
     * @return duty_bill_amt 发票金额
     */
    public BigDecimal getDutyBillAmt() {
        return dutyBillAmt;
    }

    /**
     * 发票金额
     * @param dutyBillAmt 发票金额
     */
    public void setDutyBillAmt(BigDecimal dutyBillAmt) {
        this.dutyBillAmt = dutyBillAmt;
    }

    /**
     * 
     * @return duty_createTime 
     */
    public Date getDutyCreatetime() {
        return dutyCreatetime;
    }

    /**
     * 
     * @param dutyCreatetime 
     */
    public void setDutyCreatetime(Date dutyCreatetime) {
        this.dutyCreatetime = dutyCreatetime;
    }

    /**
     * 
     * @return duty_updateTime 
     */
    public Date getDutyUpdatetime() {
        return dutyUpdatetime;
    }

    /**
     * 
     * @param dutyUpdatetime 
     */
    public void setDutyUpdatetime(Date dutyUpdatetime) {
        this.dutyUpdatetime = dutyUpdatetime;
    }

    /**
     * 状态，默认1，1-可以生成结案文件，2-成功生成结案文件，3-可以生成理赔通知书，-1-作废
     * @return duty_status 状态，默认1，1-可以生成结案文件，2-成功生成结案文件，3-可以生成理赔通知书，-1-作废
     */
    public Integer getDutyStatus() {
        return dutyStatus;
    }

    /**
     * 状态，默认1，1-可以生成结案文件，2-成功生成结案文件，3-可以生成理赔通知书，-1-作废
     * @param dutyStatus 状态，默认1，1-可以生成结案文件，2-成功生成结案文件，3-可以生成理赔通知书，-1-作废
     */
    public void setDutyStatus(Integer dutyStatus) {
        this.dutyStatus = dutyStatus;
    }

    /**
     * j保存生成文件的有关信息
     * @return duty_memo j保存生成文件的有关信息
     */
    public String getDutyMemo() {
        return dutyMemo;
    }

    /**
     * j保存生成文件的有关信息
     * @param dutyMemo j保存生成文件的有关信息
     */
    public void setDutyMemo(String dutyMemo) {
        this.dutyMemo = dutyMemo;
    }

    /**
     * 状态，默认1，0-太享福已撤案，1-可以生成结案文件，2-成功生成结案文件，3-可以生成理赔通知书，4-已完成，-1-作废 
     * @return claim_head_number 状态，默认1，0-太享福已撤案，1-可以生成结案文件，2-成功生成结案文件，3-可以生成理赔通知书，4-已完成，-1-作废 
     */
    public String getClaimHeadNumber() {
        return claimHeadNumber;
    }

    /**
     * 状态，默认1，0-太享福已撤案，1-可以生成结案文件，2-成功生成结案文件，3-可以生成理赔通知书，4-已完成，-1-作废 
     * @param claimHeadNumber 状态，默认1，0-太享福已撤案，1-可以生成结案文件，2-成功生成结案文件，3-可以生成理赔通知书，4-已完成，-1-作废 
     */
    public void setClaimHeadNumber(String claimHeadNumber) {
        this.claimHeadNumber = claimHeadNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_over_duty
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", dutyId=").append(dutyId);
        sb.append(", adjustmentguid=").append(adjustmentguid);
        sb.append(", relatedobjectguid=").append(relatedobjectguid);
        sb.append(", dutyBatchCode=").append(dutyBatchCode);
        sb.append(", dutyGroupPolicy=").append(dutyGroupPolicy);
        sb.append(", dutyClaimCode=").append(dutyClaimCode);
        sb.append(", dutyClaimCodeTb=").append(dutyClaimCodeTb);
        sb.append(", dutyCorpCode=").append(dutyCorpCode);
        sb.append(", dutyPersonCertid=").append(dutyPersonCertid);
        sb.append(", dutyVisitDuty=").append(dutyVisitDuty);
        sb.append(", dutyVisitCount=").append(dutyVisitCount);
        sb.append(", dutyApplyAmt=").append(dutyApplyAmt);
        sb.append(", dutyAbtmAmt=").append(dutyAbtmAmt);
        sb.append(", dutyCompensateAmt=").append(dutyCompensateAmt);
        sb.append(", dutyChangeAmt=").append(dutyChangeAmt);
        sb.append(", dutyResidueAmt=").append(dutyResidueAmt);
        sb.append(", dutyUnCompensateCause=").append(dutyUnCompensateCause);
        sb.append(", dutyPolicyBeginDate=").append(dutyPolicyBeginDate);
        sb.append(", dutyPolicyEndDate=").append(dutyPolicyEndDate);
        sb.append(", dutyBillType=").append(dutyBillType);
        sb.append(", dutyCompensateDuty=").append(dutyCompensateDuty);
        sb.append(", dutyCompensateRatio=").append(dutyCompensateRatio);
        sb.append(", dutyBillAmt=").append(dutyBillAmt);
        sb.append(", dutyCreatetime=").append(dutyCreatetime);
        sb.append(", dutyUpdatetime=").append(dutyUpdatetime);
        sb.append(", dutyStatus=").append(dutyStatus);
        sb.append(", dutyMemo=").append(dutyMemo);
        sb.append(", claimHeadNumber=").append(claimHeadNumber);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}
