package com.bone.tpa.sdk.masterdb.model;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

import java.io.Serializable;
import java.util.Date;

/**
 * tpa 推送影像件表
 */
@Data
public class TbPushImage implements Serializable {
    /**
     * 主键
     *
     * @mbg.generated
     */
    @Schema(description = "主键")


    @TableId(value = "id", type = IdType.AUTO)
    private Integer id;

    /**
     * 赔案号
     *
     * @mbg.generated
     */
    @Schema(description = "赔案号")
    private String claimCode;

    /**
     * 影像件名称
     *
     * @mbg.generated
     */
    @Schema(description = "影像件名称")
    private String imageName;

    /**
     * 影像件类型
     *
     * @mbg.generated
     */
    @Schema(description = "影像件类型")
    private String imageType;

    /**
     * 影像件地址
     *
     * @mbg.generated
     */
    @Schema(description = "影像件地址")
    private String imageAddress;

    /**
     * 影像件状态，与 tb_over_claim 一致
     *
     * @mbg.generated
     */
    @Schema(description = "影像件状态，与 tb_over_claim 一致")
    private Integer imageStatus;

    /**
     * 删除标志位。0: 未删除，1: 已删除
     *
     * @mbg.generated
     */
    @Schema(description = "删除标志位。0: 未删除，1: 已删除")
    private Integer isDeleted;

    /**
     * 创建时间
     *
     * @mbg.generated
     */
    @Schema(description = "创建时间")
    private Date gmtCreate;

    /**
     * 更新时间
     *
     * @mbg.generated
     */
    @Schema(description = "更新时间")
    private Date gmtUpdated;

    @Schema(description = "tb_over_claim_detail_extend id")
    private Long billId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_push_image
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 主键
     * @return id 主键
     */
    public Integer getId() {
        return id;
    }

    /**
     * 主键
     * @param id 主键
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 赔案号
     * @return claim_code 赔案号
     */
    public String getClaimCode() {
        return claimCode;
    }

    /**
     * 赔案号
     * @param claimCode 赔案号
     */
    public void setClaimCode(String claimCode) {
        this.claimCode = claimCode;
    }

    /**
     * 影像件名称
     * @return image_name 影像件名称
     */
    public String getImageName() {
        return imageName;
    }

    /**
     * 影像件名称
     * @param imageName 影像件名称
     */
    public void setImageName(String imageName) {
        this.imageName = imageName;
    }

    /**
     * 影像件类型
     * @return image_type 影像件类型
     */
    public String getImageType() {
        return imageType;
    }

    /**
     * 影像件类型
     * @param imageType 影像件类型
     */
    public void setImageType(String imageType) {
        this.imageType = imageType;
    }

    /**
     * 影像件地址
     * @return image_address 影像件地址
     */
    public String getImageAddress() {
        return imageAddress;
    }

    /**
     * 影像件地址
     * @param imageAddress 影像件地址
     */
    public void setImageAddress(String imageAddress) {
        this.imageAddress = imageAddress;
    }

    /**
     * 影像件状态，与 tb_over_claim 一致
     * @return image_status 影像件状态，与 tb_over_claim 一致
     */
    public Integer getImageStatus() {
        return imageStatus;
    }

    /**
     * 影像件状态，与 tb_over_claim 一致
     * @param imageStatus 影像件状态，与 tb_over_claim 一致
     */
    public void setImageStatus(Integer imageStatus) {
        this.imageStatus = imageStatus;
    }

    /**
     * 删除标志位。0: 未删除，1: 已删除
     * @return is_deleted 删除标志位。0: 未删除，1: 已删除
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * 删除标志位。0: 未删除，1: 已删除
     * @param isDeleted 删除标志位。0: 未删除，1: 已删除
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * 创建时间
     * @return gmt_create 创建时间
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * 创建时间
     * @param gmtCreate 创建时间
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * 更新时间
     * @return gmt_updated 更新时间
     */
    public Date getGmtUpdated() {
        return gmtUpdated;
    }

    /**
     * 更新时间
     * @param gmtUpdated 更新时间
     */
    public void setGmtUpdated(Date gmtUpdated) {
        this.gmtUpdated = gmtUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_push_image
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", claimCode=").append(claimCode);
        sb.append(", imageName=").append(imageName);
        sb.append(", imageType=").append(imageType);
        sb.append(", imageAddress=").append(imageAddress);
        sb.append(", imageStatus=").append(imageStatus);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append(", gmtCreate=").append(gmtCreate);
        sb.append(", gmtUpdated=").append(gmtUpdated);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}
