package com.bone.iam.application;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyLong;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import com.bone.iam.application.command.CreateRoleCommand;
import com.bone.iam.application.policy.TenantQuotaEnforcer;
import com.bone.iam.domain.gateway.TenantProvider;
import com.bone.iam.domain.model.role.Role;
import com.bone.iam.domain.repository.RoleRepository;
import java.lang.reflect.Field;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

/**
 * RoleApplicationService#create 单元测试（原 CreateRoleCommandHandler 逻辑已内联）。
 *
 * <p>覆盖：
 *
 * <ol>
 *   <li>正常创建角色 → 返回 ID
 *   <li>code 为空时自动从 name 生成
 *   <li>tenantId 为 null 时从 TenantProvider 端口获取
 * </ol>
 */
@ExtendWith(MockitoExtension.class)
class RoleApplicationServiceCreateTest {

  @Mock RoleRepository roleRepository;
  @Mock TenantQuotaEnforcer tenantQuotaEnforcer;
  @Mock TenantProvider tenantProvider;

  @InjectMocks RoleApplicationService roleApplicationService;

  @Test
  void createRoleWithExplicitCode() {
    CreateRoleCommand cmd = new CreateRoleCommand();
    cmd.setName("管理员");
    cmd.setCode("ADMIN_ROLE");
    cmd.setDescription("系统管理员角色");
    cmd.setTenantId(1L);

    when(roleRepository.save(any(Role.class)))
        .thenAnswer(
            invocation -> {
              Role role = invocation.getArgument(0);
              setField(role, "id", 5L);
              return role.getId();
            });

    Long result = roleApplicationService.create(cmd);

    assertThat(result).isEqualTo(5L);
    verify(tenantQuotaEnforcer, times(1)).assertCanAddRole(1L);
    verify(roleRepository, times(1)).save(any(Role.class));
  }

  @Test
  void blankCodeAutoGeneratedFromName() {
    CreateRoleCommand cmd = new CreateRoleCommand();
    cmd.setName("Data Editor");
    cmd.setCode("  ");
    cmd.setTenantId(1L);

    when(roleRepository.save(any(Role.class)))
        .thenAnswer(
            invocation -> {
              Role role = invocation.getArgument(0);
              setField(role, "id", 7L);
              return role.getId();
            });

    Long result = roleApplicationService.create(cmd);

    assertThat(result).isEqualTo(7L);
    verify(roleRepository, times(1)).save(any(Role.class));
  }

  @Test
  void nullTenantIdFallsBackToTenantProvider() {
    when(tenantProvider.currentTenantIdOrNull()).thenReturn(0L);
    CreateRoleCommand cmd = new CreateRoleCommand();
    cmd.setName("Test Role");
    cmd.setCode("TEST_ROLE");
    cmd.setTenantId(null);

    when(roleRepository.save(any(Role.class)))
        .thenAnswer(
            invocation -> {
              Role role = invocation.getArgument(0);
              setField(role, "id", 8L);
              return role.getId();
            });

    Long result = roleApplicationService.create(cmd);

    assertThat(result).isEqualTo(8L);
    verify(tenantQuotaEnforcer, times(1)).assertCanAddRole(anyLong());
  }

  private static void setField(Object obj, String name, Object value) {
    try {
      Field f = findField(obj.getClass(), name);
      f.setAccessible(true);
      f.set(obj, value);
    } catch (ReflectiveOperationException e) {
      throw new IllegalStateException(e);
    }
  }

  private static Field findField(Class<?> cls, String name) throws NoSuchFieldException {
    Class<?> c = cls;
    while (c != null) {
      try {
        return c.getDeclaredField(name);
      } catch (NoSuchFieldException ignored) {
        c = c.getSuperclass();
      }
    }
    throw new NoSuchFieldException(name);
  }
}
