<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.bone.cloud</groupId>
        <artifactId>bone-boot</artifactId>
        <version>1.0.0</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <modules>
        <module>bone-auth</module>
        <module>bone-auth-sdk</module>
        <module>bone-iam</module>
        <module>bone-gateway</module>
        <module>bone-masterdata</module>
        <module>bone-notification</module>
        <module>bone-file</module>
    </modules>
    <artifactId>bone-platform</artifactId>
    <packaging>pom</packaging>

    <name>${project.artifactId}</name>
    <description>
        ⚙️平台服务层 - 企业级共享服务
    </description>
</project>