<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.bone.cloud</groupId>
        <artifactId>bone-boot</artifactId>
        <version>1.0.0</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <modules>
        <module>bone-admin</module>
        <module>bone-api-gateway</module>
    </modules>
    <artifactId>bone-services</artifactId>
    <packaging>pom</packaging>

    <name>${project.artifactId}</name>
    <description>
        业务服务层 (service)：
        bone-admin: 管理模块。
        bone-api-gateway: api网关。
    </description>
</project>
