

spring:
  #################### 数据库相关配置 ####################
  datasource:
    url: jdbc:mysql://rds260kj5i2879nym9a9o.mysql.rds.aliyuncs.com:3306/pageconfig?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: pageconfiguser
    password: LJUHx1i#
    # 指定为HikariDataSource
    type: com.zaxxer.hikari.HikariDataSource
    # hikari连接池配置
    hikari:
      #连接池名
      pool-name: HikariCP
      #最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间，默认10分钟
      idle-timeout: 600000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 30
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认30分钟
      max-lifetime: 700000
      # 数据库连接超时时间,默认30秒
      connection-timeout: 30000
      # 连接测试query
      connection-test-query: SELECT 1

  #################### Redis相关配置 ####################
  data:
    redis:
      host: 47.105.112.106
      port: 6379
      database: 0
      password: '@Pukang_123' # 密码，建议生产环境开启
      timeout: 10s
      lettuce: # 使用lettuce连接池
        pool:
          max-active: 8  #最大连接
          max-idle: 8   #最大空闲连接
          min-idle: 0   #最小空闲连接
          max-wait: 100ms #连接等待时间

metadata:
  sdk:
    open: true
    appcode: tpa
    secret: vxOFX0Kt6Rl6YSbicgYlfg==
    #    url: http://127.0.0.1:8081
    url: http://metabata.dev6.pukangbao.com
    sqlpath: testsql/


#################### 登录模块相关配置 ####################
sa-token:
  disable: true #关闭权限功能
  sign:
    secret-key: kQwIOrYvnXmSDkwEiFngrKidMcdrgKor
  timeout: 28800
  token-name: Satoken
  alone-redis:
    database: 11
    host: 47.105.112.106
    port: 6379
    password: '@Pukang_123'
    connect-timeout: 10s

#################### eureka相关配置 ####################
eureka:
  instance:
    status-page-url: /actuator/info
    health-check-url-path: /actuator/health
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://root:root@192.168.8.136:8099/eureka/
      registry-fetch-interval-seconds: 5