server:
  port: 38081
  servlet:
    context-path: /cfg

logging:
  file:
    name: ${user.home}/logs/${spring.application.name}.log # 日志文件名，全路径



feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  application:
    name: pageConfig-server
  profiles:
    active: local
