package com.bone.tpa.sdk.masterdb.mapper;


import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.bone.tpa.sdk.masterdb.model.TbClaim;

public interface TbClaimMapper extends BaseMapper<TbClaim> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbClaim
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer tbclaimId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbClaim
     *
     * @mbg.generated
     */
    int insert(TbClaim record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbClaim
     *
     * @mbg.generated
     */
    int insertSelective(TbClaim record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbClaim
     *
     * @mbg.generated
     */
    TbClaim selectByPrimaryKey(Integer tbclaimId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbClaim
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbClaim record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbClaim
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbClaim record);
}
