package com.bone.tpa.sdk.masterdb.mapper;


import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.bone.tpa.sdk.masterdb.model.TbOverProject;


public interface TbOverProjectMapper extends BaseMapper<TbOverProject> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbOverProject
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbOverProject
     *
     * @mbg.generated
     */
    int insert(TbOverProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbOverProject
     *
     * @mbg.generated
     */
    int insertSelective(TbOverProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbOverProject
     *
     * @mbg.generated
     */
    TbOverProject selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbOverProject
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbOverProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbOverProject
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbOverProject record);

}
