package com.bone.tpa.sdk.masterdb.mapper;


import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.bone.tpa.sdk.masterdb.model.TbOverClaimConclusionExtend;


public interface TbOverClaimConclusionExtendMapper extends BaseMapper<TbOverClaimConclusionExtend> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbOverClaimConclusionExtend
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbOverClaimConclusionExtend
     *
     * @mbg.generated
     */
    int insert(TbOverClaimConclusionExtend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbOverClaimConclusionExtend
     *
     * @mbg.generated
     */
    int insertSelective(TbOverClaimConclusionExtend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbOverClaimConclusionExtend
     *
     * @mbg.generated
     */
    TbOverClaimConclusionExtend selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbOverClaimConclusionExtend
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbOverClaimConclusionExtend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbOverClaimConclusionExtend
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbOverClaimConclusionExtend record);
}
