package com.bone.tpa.sdk.masterdb.mapper;


import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.bone.tpa.sdk.masterdb.model.TbOverClaimConclusion;

public interface TbOverClaimConclusionMapper extends BaseMapper<TbOverClaimConclusion> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbOverClaimConclusion
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer conclusionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbOverClaimConclusion
     *
     * @mbg.generated
     */
    int insert(TbOverClaimConclusion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbOverClaimConclusion
     *
     * @mbg.generated
     */
    int insertSelective(TbOverClaimConclusion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbOverClaimConclusion
     *
     * @mbg.generated
     */
    TbOverClaimConclusion selectByPrimaryKey(Integer conclusionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbOverClaimConclusion
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbOverClaimConclusion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbOverClaimConclusion
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbOverClaimConclusion record);
}
