package com.bone.tpa.sdk.masterdb.mapper;


import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.bone.tpa.sdk.masterdb.model.TbOverClaim;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface TbOverClaimMapper extends BaseMapper<TbOverClaim> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbOverClaim
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer claimId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbOverClaim
     *
     * @mbg.generated
     */
    int insert(TbOverClaim record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbOverClaim
     *
     * @mbg.generated
     */
    int insertSelective(TbOverClaim record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbOverClaim
     *
     * @mbg.generated
     */
    TbOverClaim selectByPrimaryKey(Integer claimId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbOverClaim
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbOverClaim record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbOverClaim
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(TbOverClaim record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbOverClaim
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbOverClaim record);

    String sql = "select claim_claim_code,ImagingPath from TbOverClaim inner join TbOverClaim_extend on " +
            "claim_claim_code = claim_code where  claim_status != -1 and claim_createTime > '2022-01-01 00:00:00' \n" +
            "  and claim_image_is_tif = 0 and not EXISTS(select claim_number from tb_sync_claim_img_detail  where \n" +
            "TbOverClaim.claim_claim_code = tb_sync_claim_img_detail.claim_number and is_delete = 0) ORDER BY claim_id desc limit 50000";

    @Select(sql)
    List<TbOverClaim> getClaimZGRSImage();
}
