package com.bone.tpa.sdk.masterdb.mapper;


import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.bone.tpa.sdk.masterdb.model.TbOverDuty;

public interface TbOverDutyMapper extends BaseMapper<TbOverDuty> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbOverDuty
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer dutyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbOverDuty
     *
     * @mbg.generated
     */
    int insert(TbOverDuty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbOverDuty
     *
     * @mbg.generated
     */
    int insertSelective(TbOverDuty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbOverDuty
     *
     * @mbg.generated
     */
    TbOverDuty selectByPrimaryKey(Integer dutyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbOverDuty
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbOverDuty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbOverDuty
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbOverDuty record);
}
