package com.bone.tpa.sdk.masterdb.mapper;


import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.bone.tpa.sdk.masterdb.model.TbOverClaimDetail;

public interface TbOverClaimDetailMapper extends BaseMapper<TbOverClaimDetail> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbOverClaimDetail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer claimdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbOverClaimDetail
     *
     * @mbg.generated
     */
    int insert(TbOverClaimDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbOverClaimDetail
     *
     * @mbg.generated
     */
    int insertSelective(TbOverClaimDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbOverClaimDetail
     *
     * @mbg.generated
     */
    TbOverClaimDetail selectByPrimaryKey(Integer claimdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbOverClaimDetail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbOverClaimDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbOverClaimDetail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbOverClaimDetail record);
}
