package com.bone.tpa.sdk.masterdb.mapper;



import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.bone.tpa.sdk.masterdb.model.TbPushImage;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface TbPushImageMapper extends BaseMapper<TbPushImage> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbPushImage
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbPushImage
     *
     * @mbg.generated
     */
    int insert(TbPushImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbPushImage
     *
     * @mbg.generated
     */
    int insertSelective(TbPushImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbPushImage
     *
     * @mbg.generated
     */
    TbPushImage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbPushImage
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbPushImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbPushImage
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbPushImage record);
}
