package com.bone.metadata.sdk.query.builder;

import com.bone.core.domain.extension.ExtensibleObject;
import com.bone.core.util.ReflectionUtil;
import com.bone.metadata.sdk.query.context.BatchUpdateContext;
import com.bone.metadata.sdk.domain.query.BatchCompiledQuery;
import com.bone.metadata.sdk.domain.model.ColumnMetadata;
import com.bone.metadata.sdk.domain.model.TableMetadata;

import java.util.*;
import java.util.stream.Collectors;

public class BatchUpdateBuilder implements BatchQueryBuilder<BatchUpdateContext> {

    @Override
    public BatchCompiledQuery build(BatchUpdateContext ctx) {
        TableMetadata table = ctx.getTable();
        ColumnMetadata pk = table.getPrimaryKey();
        List<?> ents = ctx.getEntities();

        // 取非主键、非自生成字段作为更新列
        List<ColumnMetadata> updCols = table.getColumns().stream()
                .filter(c -> !c.isPrimaryKey() && !c.isAutoGenerated())
                .toList();

        String setClause = updCols.stream()
                .map(c -> c.getName() + " = :" + c.getName())
                .collect(Collectors.joining(", "));
        String whereTpl = pk.getName() + " = :" + pk.getName();

        String sql = "UPDATE " + table.getName() + " SET "
                + setClause + " WHERE " + whereTpl;

        List<Map<String,Object>> batch = new ArrayList<>();
        for (Object e : ents) {
            Map<String,Object> m = new LinkedHashMap<>();
            // 主键值
            m.put(pk.getName(), ReflectionUtil.getFieldValue(e, pk.getFieldName()));
            // 更新列值
            for (ColumnMetadata c : updCols) {
                m.put(c.getName(), ReflectionUtil.getFieldValue(e, c.getFieldName()));
            }
            // 扩展属性
            if (e instanceof ExtensibleObject ext) {
                ext.getExtraProperties().forEach((k,v) -> m.put("ext_"+k, v));
            }
            batch.add(m);
        }
        return new BatchCompiledQuery(sql, batch);
    }
}
